---
- name: Creates directory
  file:
    path: /etc/systemd/system/zabbix-agent.service.d
    state: directory

- name: Copy override.conf    
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'override.conf', dest: '/etc/systemd/system/zabbix-agent.service.d/override.conf' }

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart Zabbix-Agent
  service: name=zabbix-agent state=restarted 


