---

- hosts: all

  remote_user: ansible



  tasks:

    - name: modify auth required

      lineinfile: dest=/etc/pam.d/system-auth

            regexp="^auth[\s\x20]*required[\s\x20]*(pam_env.so|pam_tally2.so)"

            line="auth        required      pam_tally2.so deny=5 unlock_time=120 no_magic_root"

            state=present

      become: yes

      become_user: root  

      

    - name: modify account requisite

      lineinfile: dest=/etc/pam.d/system-auth

            regexp="^account[\s\x20]*required[\s\x20]*(pam_unix.so|pam_tally2.so)"

            line="account     required      pam_tally2.so no_magic_root reset"

            state=present

      become: yes

      become_user: root        

      

    - name: modify password requisite

      lineinfile: dest=/etc/pam.d/system-auth

            regexp="^password[\s\x20]*requisite"

            line="password    requisite     pam_cracklib.so try_first_pass retry=3 lcredit=1 dcredit=-1 ocredit=1"

            state=present

      become: yes

      become_user: root            



    - name: modify password sufficient

      lineinfile: dest=/etc/pam.d/system-auth

            regexp="^password[\s\x20]*sufficient*"

            line="password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok remember=1"

            state=present

      become: yes

      become_user: root 



    - name: modify auth required

      lineinfile: dest=/etc/pam.d/password-auth

            regexp="^auth[\s\x20]*required[\s\x20]*(pam_env.so|pam_tally2.so)[\s\x20]*"

            line="auth        required      pam_tally2.so deny=3 unlock_time=60"

            state=present

      become: yes

      become_user: root



    - name: modify account required

      lineinfile: dest=/etc/pam.d/password-auth

            regexp="^account[\s\x20]*required[\s\x20]*(pam_unix.so|pam_tally2.so)[\s\x20]*"

            line="account     required      pam_tally2.so"

            state=present

      become: yes

      become_user: root
