---

- hosts: all

  remote_user: ansible



  tasks:

    - name: modify password max days

      lineinfile: dest=/etc/login.defs

            regexp="^PASS_MAX_DAYS[\s\x20]*[0-9]*"

            line="PASS_MAX_DAYS  90"

            state=present

      become: yes

      become_user: root



    - name: modify password min days

      lineinfile: dest=/etc/login.defs

            regexp="^PASS_MIN_DAYS[\s\x20]*[0-9]*"

            line="PASS_MIN_DAYS  1"

            state=present

      become: yes

      become_user: root



    - name: modify password min length

      lineinfile: dest=/etc/login.defs

            regexp="^PASS_MIN_LEN[\s\x20]*[0-9]*"

            line="PASS_MIN_LEN    8"

            state=present

      become: yes

      become_user: root
