---
- name: Create a new host or update an existing host
  local_action: 
    module: community.zabbix.zabbix_host
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    host_name: "{{ ec2_id }}"
    visible_name: "{{ ec2_tag_Name }}"
    host_groups:
      - "{{ group }}" 
    link_templates:
      - all_os_check_linux_active
      - ALL_LOG_COLLECT
      - Template AWS CloudWatch
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ec2_private_ip_adress }}"
        port: "10050"
        dns: "{{ private_dns_name }}"
    macros:
      - macro: '{$AWS.ACCOUNT}'
        value: "{{ ec2_account_id }}"
      - macro: '{$AWS.REGION}'
        value: "{{ ec2_region }}"
    tags:
      - tag: Instance_ID
        value: "{{ ec2_id }}"
      - tag: Instance_Type
        value: "{{ ec2_instance_type }}"
      - tag: VPC_ID
        value: "{{ ec2_vpc_id }}"
      - tag: Region_Name
        value: "{{ ec2_region }}"
      - tag: Availability_zone
        value: "{{ ec2_placement }}"
      - tag: Subnet_ID
        value: "{{ ec2_subnet_id }}"
      - tag: Private_IP
        value: "{{ ec2_private_ip_adress }}"
      - tag: Public_IP
        value: "{{ ec2_ip_address }}"
      - tag: Security_Group
        value: "{{ ec2_security_group_names }}"
      - tag: Launch_Time
        value: "{{ ec2_launch_time }}"
