---
- name: Copy Zabbix Agent rpm to host
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'zabbix-agent-5.0.3-1.el7.x86_64.rpm', dest: 'zabbix-agent-5.0.3-1.el7.x86_64.rpm' }
    - { src: 'scripts', dest: '/etc/zabbix/scripts' }
    - { src: 'zabbix_agentd.d', dest: '/etc/zabbix/zabbix_agentd.d' }

- name: Install Zabbix Agent
  package:
          name: zabbix-agent-5.0.3-1.el7.x86_64.rpm
          state: present

- name: Configure Zabbix Agent
  template:
          src: 02-zabbix_agentd.conf.j2
          dest: /etc/zabbix/zabbix_agentd.conf
          owner: root
          group: root
          backup: yes

- name: Start Zabbix Agent
  service: name=zabbix-agent state=started enabled=yes
