---
- name: Test Connection
  ping:

- name: Install Zabbix Agent (Ubuntu 16.04)
  include_tasks: "01-ubuntu16-install-zabbix-agent.yml"
  when:
    - ansible_pkg_mgr == "apt" and ansible_distribution_major_version == "16"

- name: Install Zabbix Agent (Ubuntu 18.04)
  include_tasks: "02-ubuntu18-install-zabbix-agent.yml"
  when:
    - ansible_pkg_mgr == "apt" and ansible_distribution_major_version == "18"

- name: Install Zabbix Agent (Ubuntu 20.04)
  include_tasks: "03-ubuntu20-install-zabbix-agent.yml"
  when:
    - ansible_pkg_mgr == "apt" and ansible_distribution_major_version == "20"

- name: Install Zabbix Agent (CentOS 6)
  include_tasks: "04-rhel6-install-zabbix-agent.yml"
  when:
    - ansible_pkg_mgr == "yum" and ansible_distribution_major_version == "6" or ansible_distribution == "Amazon" and ansible_distribution_major_version == "1"

- name: Install Zabbix Agent (CentOS 7)
  include_tasks: "05-rhel7-install-zabbix-agent.yml"
  when:
    - ansible_pkg_mgr == "yum" and ansible_distribution_major_version == "7" or ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name : Create Zabbix Hosts
  include_tasks: 07-create-zabbix-host.yml

