- name: modify password max days
  lineinfile:
    path: '/etc/login.defs'
    regexp: '^PASS_MAX_DAYS[\s\x20]*[0-9]*'
    line: 'PASS_MAX_DAYS  90'
    state: present

- name: modify password min days
  lineinfile:
    path: '/etc/login.defs'
    regexp: '^PASS_MIN_DAYS[\s\x20]*[0-9]*'
    line: 'PASS_MIN_DAYS  1'
    state: present
